apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: "example-app"
  labels:
    app.kubernetes.io/name: "example-app"
spec:
  descriptor:
    links:
      - description: 'Launch'
        url: "http://example-nginx"
