apiVersion: kots.io/v1beta1
kind: HelmChart
metadata:
  name: wordpress-enterprise
spec:
  chart:
    name: replicated-starter-kots
    chartVersion: 0.1.0

  # helmVersion identifies the Helm Version used to render the chart. Default is v2.
  helmVersion: v3

  # useHelmInstall identifies whether this Helm chart will use the
  # Replicated Helm installation (false) or native Helm installation (true). Default is false.
  # Native Helm installations are only available for Helm v3 charts.
  useHelmInstall: true

  # weight determines the order that charts with "useHelmInstall: true" are applied, with lower weights first.
  weight: 0

  # values are used in the customer environment, as a pre-render step
  # these values will be supplied to helm template
  values: {}
